name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: configure
        displayName: Configure
        steps:
          - task: PowerShell@2
            displayName: Set build identifier
            name: setNPMBuildIdentifier
            inputs:
              targetType: inline
              script: Write-Host "##vso[build.updatebuildnumber]1.0.$(build.buildid)-$(System.StageAttempt)"
              errorActionPreference: default
              showWarnings: true
              pwsh: true
      - job: postman
        displayName: Postman
        dependsOn: configure
        steps:
          - task: Npm@1
            displayName: Restore
            inputs:
              command: 'ci'
              workingDir: 'working folder'
          - task: Npm@1
            displayName: Build
            inputs:
              command: 'custom'
              workingDir: 'working folder'
              customCommand: 'build'
          - task: ArchiveFiles@2
            displayName: Zip
            inputs:
              rootFolderOrFile: 'working folder'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: 'postman.$(Build.BuildId).zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: Publish archive
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/as'
              ArtifactName: 'postman.build identifier'
              publishLocation: 'Container'

  - stage: production
    displayName: Production
    dependsOn: build
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
      - name: WORKSPACE_PREFIX
        value: codedeploy-
    jobs:
      - template: terraform/plan-and-approve.yml@templates
        parameters:
          artifactName: ${{ variables.TF_ARTIFACT_NAME }}
          environment: ${{ variables.ENVIRONMENT }}
          workspaceName: ${{ variables.WORKSPACE_PREFIX }}${{ variables.ENVIRONMENT }}
