name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: terraform-templates
      type: github
      name: expensely/infra-terraform-backend
      endpoint: expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: configure
        displayName: Configure
        steps:
          - checkout: none
          - task: PowerShell@2
            displayName: Set build identifier
            name: setNPMBuildIdentifier
            inputs:
              targetType: inline
              script: Write-Host "##vso[build.updatebuildnumber]1.0.$(build.buildid)-$(System.StageAttempt)"
              errorActionPreference: default
              showWarnings: true
              pwsh: true
      - job: postman
        displayName: Postman
        dependsOn: configure
        steps:
          - task: NodeTool@0
            displayName: Install Node:14
            inputs:
              versionSpec: 14
          - task: Npm@1
            displayName: Restore
            inputs:
              command: ci
              workingDir: $(Build.SourcesDirectory)/lambdas/postman
          - task: Npm@1
            displayName: Build
            inputs:
              command: custom
              workingDir: $(Build.SourcesDirectory)/lambdas/postman
              customCommand: run build
            env:
              BUILD_NUMBER: $(Build.BuildNumber)
          - task: ArchiveFiles@2
            displayName: Zip
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)/lambdas/postman
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.SourcesDirectory)/lambdas/postman/postman.zip
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: Publish archive
            inputs:
              PathtoPublish: $(Build.SourcesDirectory)/lambdas/postman/postman.zip
              ArtifactName: postman
              publishLocation: Container

  - stage: preview
    displayName: Preview
    dependsOn: build
    variables:
      - group: terraform.platform.preview
    jobs:
      - template: pipelines/templates/plan-and-approve.yml@terraform-templates
        parameters:
          terraformVariablesFile: variables/time.preview.ap-southeast-2.tfvars
          terraformWorkspace: codedeploy_time_preview
          environment: Preview
          terraformArtifactName: time.$(TF_ARTIFACT_NAME)

  - stage: production
    displayName: Production
    dependsOn: preview
    variables:
      - group: terraform.platform.production
    jobs:
      - template: pipelines/templates/plan-and-approve.yml@terraform-templates
        parameters:
          terraformVariablesFile: variables/time.production.ap-southeast-2.tfvars
          terraformWorkspace: codedeploy_time_production
          environment: Production
          terraformArtifactName: time.$(TF_ARTIFACT_NAME)
